### ISSUE TITLE
Add contact form to /contact

### ISSUE THREAD

**Issue by DavyDev** [IvanChou/hugo-theme-vec#1]
Hi dev. I am a new fan of Hugo engine and have read almost all part of the documentations. When I started a test page and take a look to themes.gohugo.io, I firstly put my eye on this cool simple theme. I like the design and its simplicity. However, I think it would be better if I could add a contact form (such as by formspree) to the /contact page.

I have tried inserting the <form> code snippet by formspree into many files (trial and error) [such as in /page/single.html] and it appears I would need a humble support by the theme creator himself.

Could you tell me a brief guide on how to do so? It would be greatly appreciated 😉

**Comment by IvanChou** [comment]
In fact, I have the same need like you, just take a look at my [/contact](https://yii.im/about/) page. It's a flood in the clear spring.  😅 😅

I'll try to add formspree into the theme in the weekend. Thank you for your suggestion.

**Comment by IvanChou** [comment]
In fact, I have the same need.
I have not known a service like formspree. That is a great suggestion.
I'll try to add the feature in the weekend. 
Thank you 😆

**Comment by DavyDev** [comment]
Great, let me know your updates 😄 
In addition, can I know what's next I need to learn before being able to make a hugo theme like yours? (beside HTML , CSS and JS)
Thanks. 👍

**Comment by IvanChou** [comment]
Read others' theme codes by hugo's docs.  http://gohugo.io/overview/introduction/
That's enough 😄
