### ISSUE TITLE
Vec Theme Demo on Hugo website contains 3rd party tracking

### ISSUE THREAD

**Issue by onedrawingperday** [IvanChou/hugo-theme-vec#15]
Hello @IvanChou 

I am one of the maintainers of the [Hugo Themes](https://github.com/gohugoio/hugoThemes/) repository.

Recently I audited the Hugo Themes website and it has [come to my attention](https://github.com/gohugoio/hugoThemes/issues/535) that your theme's demo has third party tracking enabled.

```
     \hugo-theme-vec\exampleSite\config.toml:
        disqusShortname = "yiiim"
        googleAnalytics = "UA-57408564-1"
```

To fix this issue please leave the above parameters blank i.e.

```
     \hugo-theme-vec\exampleSite\config.toml:
        disqusShortname = ""
        googleAnalytics = ""
```

Once you look into this please let me know.

Thank you!

**Comment by yiichou** [comment]
Thank you for your reminder, already removed.

**Comment by onedrawingperday** [comment]
@IvanChou 

Thank you for the fix! 👍
