### ISSUE TITLE
Header styling for post link does not work

### ISSUE THREAD

**Issue by discursivemoth** [IvanChou/hugo-theme-vec#7]
In the header partial

`<li class="pull-left {{ if eq $name $title }}current{{ else if eq $section $name }}current{{ end }}">`

works to give the "current" class to the FAQ and contact part, but not the post link. As seen on the demo site when on the post listing page "~/post" does not change to a brighter color.

**Comment by discursivemoth** [comment]
Figured it out I think. Everything works correctly if you create a _index.md file in the post section and copy layouts/_default/list.html to layouts/_default/section.html

**Comment by IvanChou** [comment]
YES! That's a BUG

I have fixed it in another way.   2d393dbad499954a398e970e4c21728f3395d483
